apiVersion: skaffold/v2alpha2
kind: Config
build:
  artifacts:
  - image: payment-gateway-api
  tagPolicy:
    sha256: {}
deploy:
  helm:
    releases:
    - name: payment-gateway-api
      chartPath: k8s
      valuesFiles:
      - k8s/values/development.yaml
      # - .env.skaffold.yaml
      values:
        image: payment-gateway-api
